# This checks for regressions caused by changes in Cygwin.

name: Daily build of latest release

on:
  schedule:
    # Randomly generated time.
    - cron: '46 5 * * *'

jobs:
  build-test:
    uses: cygporter/workflows/.github/workflows/build-test.yml@v2
    with:
      cygport_file: git.cygport
